# Generated by Django 3.1.1 on 2020-10-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orderupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ampount',
            field=models.IntegerField(default='0', max_length=100),
        ),
    ]
