# Generated by Django 3.1.1 on 2020-10-14 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orders_ampount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='ampount',
            new_name='amount',
        ),
    ]
