# Generated by Django 3.1.1 on 2020-10-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20201021_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='items_json',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
